### ISSUE TITLE
Cannot get QImpUE to compile in a new C++ project 

### ISSUE THREAD

**Issue by HeadClot** [QFormatPlugins/Qnreal#1]
Hey @tinogoehlert I made a new project called Compilepls2, I cannot seem to get the plugin to compile. I have uploaded the Log file for it. 

[CompilePls2.log](https://github.com/user-attachments/files/16808483/CompilePls2.log)

**Comment by tinogoehlert** [comment]
the wrapper code used for the csharp binding seems to cause problems on windows in unreal. i've removed it because we don't need it here :-)

**Comment by HeadClot** [comment]
Awesome thank you for the quick fix :)
